runtime: python27
api_version: 2
threadsafe: true

handlers:
- url: /.*
  script: python1.app                                                          
                                                                                
                                                                                  
                                                                                
                                                                                 
                                                                                  
                                                                                  
                                                                                  
                                                                                  
                                                                                                      





