runtime: python36
api_version: 3
threadsafe: true
handlers:
- url: /.*
  script: python1.app       
                                                                               
                                                                               
                                                                                  
                                                                                
                                                                                  
                                                                                
                                                                                 
                                                                                  
                                                                                  
                                                                                  
                                                                                  
                                                                                                      





